project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "posts/**/*.qmd"

website:
  title: "Landon Teeter"
  description: "Graduate Student in the Biochemistry, Microbiology, and Molecular Biology Department at The Pennsylvania State University"
  navbar:
    left:
      - href: index.qmd
        text: CV
      - href: blog.qmd
        text: Blog

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
